export const NEW_TODO_ITEM_TITLE_CHANGE = 'NEW_TODO_ITEM_TITLE_CHANGE';
export const TO_DO_ITEM = 'TO_DO_ITEM';
export const TO_DO_CHECK_CHANGE = 'TO_DO_CHECK_CHANGE';
export const NEW_TODO_ITEM_DEADLINE_CHANGE = 'NEW_TODO_ITEM_DEADLINE_CHANGE';
export const TO_All_SELECT = 'TO_All_SELECT';

